'use client'

import { useState, useEffect } from 'react'
import { createClientComponentClient } from '@supabase/auth-helpers-nextjs'
import { ClipboardList, UserPlus, CheckCircle, Clock, AlertTriangle } from 'lucide-react'
import { assignHandoffAction, completeHandoffAction } from './actions'

export function HandoffsClient() {
  const [handoffs, setHandoffs] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [currentUser, setCurrentUser] = useState<any>(null)
  const supabase = createClientComponentClient()

  useEffect(() => {
    supabase.auth.getUser().then(({ data: { user } }: { data: { user: any } }) => {
      setCurrentUser(user)
    })
    fetchHandoffs()

    const channel = supabase
      .channel('handoff-updates')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'team_handoffs' }, () => {
        fetchHandoffs()
      })
      .subscribe()

    return () => {
      supabase.removeChannel(channel)
    }
  }, [supabase])

  async function fetchHandoffs() {
    setLoading(true)
    const { data, error } = await supabase
      .from('team_handoffs')
      .select('*, leads(first_name, last_name, company_name)')
      .order('created_at', { ascending: false })

    if (!error && data) {
      setHandoffs(data)
    }
    setLoading(false)
  }

  async function handleAssignToMe(id: string) {
    if (!currentUser) return
    try {
      await assignHandoffAction(id, currentUser.id)
    } catch (error) {
      console.error(error)
      alert("Failed to assign handoff")
    }
  }

  async function handleComplete(id: string) {
    try {
      await completeHandoffAction(id)
    } catch (error) {
      console.error(error)
      alert("Failed to complete handoff")
    }
  }

  const activeHandoffs = handoffs.filter(h => h.status !== 'completed')
  const completedHandoffs = handoffs.filter(h => h.status === 'completed')

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-gray-900 tracking-tight flex items-center gap-3">
          <ClipboardList className="w-8 h-8 text-blue-600" />
          Team Handoffs
        </h1>
        <p className="text-gray-500 mt-2">
          Post-call briefings and internal tasks generated by the AI Voice Prep Crew.
        </p>
      </div>

      <div className="space-y-6">
        <h2 className="text-xl font-semibold text-gray-900 border-b pb-2">Active Handoffs ({activeHandoffs.length})</h2>
        {loading ? (
          <div className="text-sm text-gray-500 animate-pulse">Loading handoffs...</div>
        ) : activeHandoffs.length === 0 ? (
          <div className="bg-white rounded-xl border border-gray-200 p-8 text-center">
            <ClipboardList className="w-12 h-12 text-gray-300 mx-auto mb-3" />
            <h3 className="text-sm font-medium text-gray-900">No active handoffs</h3>
            <p className="text-sm text-gray-500 mt-1">All post-call tasks have been completed.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {activeHandoffs.map(handoff => (
              <div key={handoff.id} className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden flex flex-col">
                <div className="p-5 border-b border-gray-100 bg-gray-50/50 flex justify-between items-start">
                  <div>
                    <h3 className="font-medium text-gray-900">
                      {handoff.leads?.company_name} 
                      <span className="text-gray-500 font-normal ml-2">
                        ({handoff.leads?.first_name} {handoff.leads?.last_name})
                      </span>
                    </h3>
                    <div className="flex items-center gap-2 mt-2">
                      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                        handoff.status === 'open' ? 'bg-yellow-100 text-yellow-800' : 'bg-blue-100 text-blue-800'
                      }`}>
                        <Clock className="w-3 h-3 mr-1" />
                        {handoff.status === 'open' ? 'Unassigned' : 'In Progress'}
                      </span>
                    </div>
                  </div>
                  
                  {handoff.status === 'open' ? (
                    <button
                      onClick={() => handleAssignToMe(handoff.id)}
                      className="inline-flex items-center px-3 py-1.5 border border-gray-300 shadow-sm text-xs font-medium rounded text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                    >
                      <UserPlus className="w-4 h-4 mr-1" />
                      Assign to me
                    </button>
                  ) : (
                    <button
                      onClick={() => handleComplete(handoff.id)}
                      className="inline-flex items-center px-3 py-1.5 border border-transparent shadow-sm text-xs font-medium rounded text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                    >
                      <CheckCircle className="w-4 h-4 mr-1" />
                      Mark Complete
                    </button>
                  )}
                </div>
                
                <div className="p-5 space-y-4 flex-1">
                  <div>
                    <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Call Summary</h4>
                    <p className="text-sm text-gray-800 bg-gray-50 p-3 rounded-md border border-gray-100">
                      {handoff.brief?.summary || 'No summary available.'}
                    </p>
                  </div>
                  
                  {handoff.brief?.objections?.length > 0 && (
                    <div>
                      <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1 flex items-center gap-1">
                        <AlertTriangle className="w-3 h-3 text-orange-500" />
                        Key Objections
                      </h4>
                      <ul className="list-disc pl-5 space-y-1">
                        {handoff.brief.objections.map((obj: string, i: number) => (
                          <li key={i} className="text-sm text-gray-700">{obj}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  <div>
                    <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Generated Tasks</h4>
                    <div className="space-y-2">
                      {handoff.tasks?.map((task: any, i: number) => (
                        <div key={i} className="bg-white border border-gray-200 rounded-md p-3">
                          <div className="flex justify-between items-start">
                            <span className="text-sm font-medium text-gray-900">{task.title}</span>
                            <span className={`inline-flex px-2 py-0.5 rounded text-[10px] font-medium uppercase ${
                              task.priority === 'high' ? 'bg-red-100 text-red-800' :
                              task.priority === 'medium' ? 'bg-yellow-100 text-yellow-800' :
                              'bg-green-100 text-green-800'
                            }`}>
                              {task.priority}
                            </span>
                          </div>
                          <p className="text-xs text-gray-500 mt-1">{task.description}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {completedHandoffs.length > 0 && (
        <div className="space-y-4 pt-8">
          <h2 className="text-xl font-semibold text-gray-900 border-b pb-2">Completed Handoffs</h2>
          <div className="bg-white shadow overflow-hidden sm:rounded-md border border-gray-200">
            <ul role="list" className="divide-y divide-gray-200">
              {completedHandoffs.map(handoff => (
                <li key={handoff.id}>
                  <div className="px-4 py-4 sm:px-6">
                    <div className="flex items-center justify-between">
                      <p className="text-sm font-medium text-gray-900 truncate">
                        {handoff.leads?.company_name}
                      </p>
                      <div className="ml-2 flex-shrink-0 flex">
                        <p className="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                          Completed
                        </p>
                      </div>
                    </div>
                    <div className="mt-2 sm:flex sm:justify-between">
                      <div className="sm:flex">
                        <p className="flex items-center text-sm text-gray-500">
                          {handoff.tasks?.length || 0} tasks resolved
                        </p>
                      </div>
                      <div className="mt-2 flex items-center text-sm text-gray-500 sm:mt-0">
                        <p>
                          {new Date(handoff.updated_at).toLocaleDateString()}
                        </p>
                      </div>
                    </div>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        </div>
      )}
    </div>
  )
}
