#!/bin/bash
# Task 27: GitHub MCP self-PR workflow stub
# This script automates the creation of a PR for the current changes.

BRANCH_NAME="agent-update-$(date +%s)"
git checkout -b "$BRANCH_NAME"
git add .
git commit -m "chore: automated agent update and polish"
git push origin "$BRANCH_NAME"

gh pr create \
  --title "Agent Update: Phase 4 Polish" \
  --body "Automated PR generated by SalesOS Agent. Covers frontend polish, dashboard updates, and safety guardrails." \
  --base main \
  --head "$BRANCH_NAME"

git checkout main
echo "PR created successfully on branch $BRANCH_NAME"
